export const citas = [
   {"autor": "Albert Einstein", "cita": "La vida es como andar en bicicleta. Para mantener el equilibrio, debes seguir avanzando."},
   {"autor": "Isaac Newton", "cita": "Si he visto más lejos es porque estoy parado sobre los hombros de gigantes."},
   {"autor": "Leonardo da Vinci", "cita": "El aprendizaje nunca agota la mente."},
   {"autor": "Galileo Galilei", "cita": "No puedes enseñar nada a un hombre; solo puedes ayudarlo a encontrar la respuesta dentro de sí mismo."},
   {"autor": "Marie Curie", "cita": "Nada en la vida debe ser temido, solo comprendido."},
   {"autor": "Nikola Tesla", "cita": "El presente es de ustedes, pero el futuro, por el que tanto he trabajado, me pertenece."},
   {"autor": "Stephen Hawking", "cita": "La inteligencia es la habilidad de adaptarse al cambio."},
   {"autor": "Aristóteles", "cita": "Somos lo que hacemos repetidamente. La excelencia, entonces, no es un acto, sino un hábito."},
   {"autor": "Platón", "cita": "La necesidad es la madre de la invención."},
   {"autor": "Sócrates", "cita": "Solo sé que no sé nada."},
   {"autor": "Confucio", "cita": "Elige un trabajo que te guste y nunca tendrás que trabajar un día en tu vida."},
   {"autor": "Buda", "cita": "No lastimes a los demás con lo que te causa dolor a ti mismo."},
   {"autor": "Benjamin Franklin", "cita": "Dime y lo olvido, enséñame y lo recuerdo, involúcrame y lo aprendo."},
   {"autor": "Mark Twain", "cita": "El secreto de avanzar es comenzar."},
   {"autor": "Winston Churchill", "cita": "El éxito no es definitivo, el fracaso no es fatal: lo que cuenta es el valor para continuar."},
   {"autor": "Nelson Mandela", "cita": "La educación es el arma más poderosa que puedes usar para cambiar el mundo."},
   {"autor": "Mahatma Gandhi", "cita": "Sé el cambio que quieres ver en el mundo."},
   {"autor": "Thomas Edison", "cita": "No he fallado. Solo he encontrado 10,000 formas que no funcionan."},
   {"autor": "Pablo Picasso", "cita": "La acción es la clave fundamental de todo éxito."},
   {"autor": "Vincent Van Gogh", "cita": "Si oyes una voz dentro de ti que dice 'no puedes pintar', entonces pinta y esa voz será silenciada."},
   {"autor": "Abraham Lincoln", "cita": "La mejor forma de predecir el futuro es crearlo."},
   {"autor": "Theodore Roosevelt", "cita": "Haz lo que puedas, con lo que tienes, donde estés."},
   {"autor": "Ralph Waldo Emerson", "cita": "No vayas por donde el camino te lleve, ve en cambio por donde no hay camino y deja un rastro."},
   {"autor": "Oprah Winfrey", "cita": "Crea la visión más grandiosa posible para tu vida, porque te conviertes en lo que crees."},
   {"autor": "Steve Jobs", "cita": "La única forma de hacer un gran trabajo es amar lo que haces."},
   {"autor": "Bill Gates", "cita": "Está bien celebrar el éxito, pero es más importante prestar atención a las lecciones del fracaso."},
   {"autor": "Elon Musk", "cita": "Cuando algo es lo suficientemente importante, lo haces incluso si las probabilidades no están a tu favor."},
   {"autor": "J.K. Rowling", "cita": "No necesitamos magia para cambiar el mundo, ya llevamos todo el poder que necesitamos dentro de nosotros mismos."},
   {"autor": "Malala Yousafzai", "cita": "Un niño, un maestro, un libro y un lápiz pueden cambiar el mundo."},
   {"autor": "Carl Sagan", "cita": "En algún lugar, algo increíble está esperando a ser descubierto."},
   {"autor": "Richard Feynman", "cita": "El primer principio es que no debes engañarte a ti mismo, y eres la persona más fácil de engañar."},
   {"autor": "Sun Tzu", "cita": "El supremo arte de la guerra es someter al enemigo sin luchar."},
   {"autor": "Lao Tsé", "cita": "Un viaje de mil millas comienza con un solo paso."},
   {"autor": "René Descartes", "cita": "Pienso, luego existo."},
   {"autor": "Friedrich Nietzsche", "cita": "Lo que no nos mata nos hace más fuertes."},
   {"autor": "Jean-Paul Sartre", "cita": "El hombre está condenado a ser libre."},
   {"autor": "Blaise Pascal", "cita": "El corazón tiene razones que la razón desconoce."},
   {"autor": "Sigmund Freud", "cita": "La voz de la inteligencia es suave, pero no descansa hasta ser escuchada."},
   {"autor": "Johann Wolfgang von Goethe", "cita": "Lo que no se empieza hoy nunca se terminará mañana."},
   {"autor": "Hermann Hesse", "cita": "Algunas veces hay que seguir caminos que no tienen destino conocido."},
   {"autor": "Dale Carnegie", "cita": "Recuerda que el nombre de una persona es para ella el sonido más dulce e importante en cualquier idioma."},
   {"autor": "Henry Ford", "cita": "Tanto si crees que puedes como si crees que no puedes, tienes razón."},
   {"autor": "Ray Bradbury", "cita": "Ama lo que haces y haz lo que amas."},
   {"autor": "Bruce Lee", "cita": "No reces por una vida fácil, reza por la fuerza para soportar una difícil."},
   {"autor": "Nelson Mandela", "cita": "Siempre parece imposible hasta que se hace."}
]